services:
#    doctrine.instance_listener:
#        class: AppBundle\EventListener\InstanceListener
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }

    form_serializer:
        class:        AppBundle\Utils\FormErrorsSerializer

    app.bruteforce.action_listener:
        class: AppBundle\EventListener\BruteForceListener
        arguments: [@snc_redis.default]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }